### ISSUE TITLE
proposal: add attribute to make ignoring links easier

### ISSUE THREAD

**Issue by ungoldman** [choojs/nanohref#11]
Right now the easiest way to ignore a regular link for the same domain is to add a click handler.

Example:

```js
const html = require('nanohtml')

module.exports = () => html`
  <a href="/" onclick=${home}>home</a>
`

function home (e) {
  e.preventDefault()
  window.location = '/'
}
```

This is not a lot of code, but does feel a bit cumbersome to make a link behave like a link when `nanohref` is active on a page.

I think it would be nice for users if we added a simple data attribute to accomplish the same thing.

Example:

```js
const html = require('nanohtml')

module.exports = () => html`
  <a href="/" data-nanohref="false">home</a>
`
```

Please let me know if this makes sense to maintainers! This would most likely be a one-line PR. Suggestions on naming convention for such an attribute are also welcome.

---

**Edit:** a boolean data attribute might make more sense, e.g.

```html
<a href="/" data-nanohref-ignore>home</a>
```

**Comment by yoshuawuyts** [comment]
This sounds reasonable!

**Comment by ungoldman** [comment]
PR opened! --> #12 

Went with `data-nanohref-ignore` boolean attribute
