### ISSUE TITLE
Add test and/or little demo

### ISSUE THREAD

**Issue by davidtheclark** [choojs/nanohref#3]
Even though it's a small library, there are still a few ways that the code could go wrong. What do you think about adding some tests?

Or if not automated tests, a little demo you could run for manual testing when creating a PR?

I'm happy to help out with this but don't want to start without getting some sense of your interest and your preferences (in terms of the many runners, frameworks, etc. available, and the general nastiness of getting a good in-browser test all set up).

**Comment by yoshuawuyts** [comment]
Yeah, a `tape-run` + `tape` based set of tests would be amazing! - sorry 'bout my late reply, wasn't getting any notifications for this repo. Would you want to tackle this? Happy to provide pointers!

**Comment by davidtheclark** [comment]
@yoshuawuyts :wave: worried that this repo wasn't getting attention I created https://github.com/mapbox/link-hijacker. Pretty much the same thing, with a little influence from other libraries, some options, and some tests.

**Comment by yoshuawuyts** [comment]
Oh dang, haha - I just published a whole bunch more patches; but I like
some of the additions you've added to that repo. It looks like you're not
doing any of the [data-no-routing] stuff are you? Just skipping links
pointing to other hosts + target=_blank? I def dig that.

Would for sure be cool if we could keep our sources somewhat in sync;
perhaps with nanohref being a no-config version of link-hijacker. Anyway,
added you as an owner to nanohref. Thanks!

**Comment by davidtheclark** [comment]
> Would for sure be cool if we could keep our sources somewhat in sync;
perhaps with nanohref being a no-config version of link-hijacker. 

This would be awesome! Maybe I should add to link-hijacker https://github.com/yoshuawuyts/nanohref/commit/63ef3cef879ea163b132f032a5f58c79708bbaf1 — didn't know about that problem, maybe `host` isn't available in IE?

Besides that point anything else you think would need to be added? If you're interested I could certainly submit a PR making nanohref a no-config wrapper!

**Comment by yoshuawuyts** [comment]
> If you're interested I could certainly submit a PR making nanohref a no-config wrapper!

haha, well since we focus on module size a lot, I think having it just be in-source might be better.

> Besides that point anything else you think would need to be added?

No, don't think so! - Thinking of making this a semver major, and adding it to the choo 6 release :sparkles: https://github.com/yoshuawuyts/choo/issues/519

**Comment by yoshuawuyts** [comment]
Also catch `rel="noopener"` as `target="_blank"` is not recommended

**Comment by davidtheclark** [comment]
> well since we focus on module size a lot, I think having it just be in-source might be better.

I'm not sure what you're suggesting here ... would you mind re-stating?

**Comment by yoshuawuyts** [comment]
I don't think wrapping your module is the right way for this module. I
think copying parts of the source is better. Wrapping would create dead
code for this module, which is something we try and avoid (:

**Comment by davidtheclark** [comment]
@yoshuawuyts: Ok, I get it, thanks 👍

**Comment by yoshuawuyts** [comment]
Think we're good to close this. Thanks for the chats! :grin:
