### ISSUE TITLE
origin is undefined in Microsoft Edge

### ISSUE THREAD

**Issue by seangenabe** [choojs/nanohref#7]
The `origin` property seems to be undefined in Microsoft Edge. This results in `e.preventDefault()` not being fired when appropriate.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12236493/

**Comment by yoshuawuyts** [comment]
Oh no, this is not good. A similar workaround like in
https://github.com/angular/angular.js/pull/16031 when origin isn't
available might make a lot of sense. Thanks!
